"""Add due date to tasks

Revision ID: 123b630c4fac
Revises: 2c2840b2776c
Create Date: 2026-07-11 12:25:03.156239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '123b630c4fac'
down_revision = '2c2840b2776c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('due_date')

    # ### end Alembic commands ###
