"""add description to hive

Revision ID: 45fdcf9b0a78
Revises: 99e66fb7baa0
Create Date: 2026-07-20 22:39:25.730728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45fdcf9b0a78'
down_revision = '99e66fb7baa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hive', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('hive', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
