"""Allow activity without hive

Revision ID: 99e66fb7baa0
Revises: 01fd81d6a775
Create Date: 2026-07-19 18:59:49.426151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99e66fb7baa0'
down_revision = '01fd81d6a775'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.alter_column('hive_id',
               existing_type=sa.INTEGER(),
               nullable=True)


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.alter_column('hive_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
