"""Add priority to tasks

Revision ID: dc3dfd2bfa1d
Revises: 62eb39cbaff3
Create Date: 2026-07-11 18:35:54.498570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc3dfd2bfa1d'
down_revision = '62eb39cbaff3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.String(length=20), nullable=True))

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.String(length=20), nullable=True))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('priority')

    with op.batch_alter_table('personal_tasks', schema=None) as batch_op:
        batch_op.drop_column('priority')

    # ### end Alembic commands ###
